# Generated by Django 5.2.1 on 2025-05-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=50, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marca', models.CharField(max_length=50, verbose_name='Nombre Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo', models.CharField(max_length=30, verbose_name='Nombre Tipo Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prod', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('desc_prod', models.CharField(max_length=1500, verbose_name='Descripción Producto')),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Producto')),
                ('marca_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marca', verbose_name='Marca Producto')),
                ('tag_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria', verbose_name='Categoría Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom_usuario', models.CharField(max_length=150, verbose_name='Nombre Usuario')),
                ('correo_usuario', models.EmailField(max_length=254, unique=True, verbose_name='Correo Usuario')),
                ('recibe_ofertas', models.BooleanField(default=False, verbose_name='Recibe Ofertas')),
                ('telefono_usuario', models.CharField(max_length=20, verbose_name='Teléfono Usuario')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipo_usuario', verbose_name='Tipo Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
