# Generated by Django 5.2.1 on 2025-05-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=100)),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
