# Generated by Django 5.2.1 on 2025-05-21 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=50, verbose_name='Nombre del Banco')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comuna', models.CharField(max_length=100, verbose_name='Nombre Comuna')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_estado_despacho', models.CharField(max_length=50, verbose_name='Nombre Estado Despacho')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado_pedido', models.CharField(max_length=50, verbose_name='Estado del Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo_pago', models.CharField(max_length=50, verbose_name='Tipo de Pago')),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='desc_prod',
            new_name='desc_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca_prod',
            new_name='marca_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nom_prod',
            new_name='nom_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_prod',
            new_name='precio_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tag_prod',
            new_name='tag_producto',
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_producto', models.ImageField(upload_to='productos/', verbose_name='Imagen del Producto')),
                ('puesto_imagen', models.PositiveIntegerField(verbose_name='Puesto de Imagen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(verbose_name='Fecha del Pedido')),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total del Pedido')),
                ('estado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.estadopedido', verbose_name='Estado del Pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_productos', models.PositiveIntegerField(verbose_name='Cantidad de Productos')),
                ('subtotal_producto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido', verbose_name='Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_despacho', models.CharField(max_length=255, verbose_name='Dirección de Despacho')),
                ('fecha_despacho', models.DateField(verbose_name='Fecha de Despacho')),
                ('estado_despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.estadodespacho', verbose_name='Estado del Despacho')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pedido', verbose_name='Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sucursal', models.CharField(max_length=100, verbose_name='Nombre Sucursal')),
                ('direccion_sucursal', models.CharField(max_length=255, verbose_name='Dirección Sucursal')),
                ('comuna_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.comuna', verbose_name='Comuna Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock Disponible')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto', verbose_name='Producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sucursal', verbose_name='Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_informe', models.DateField(verbose_name='Fecha del Informe')),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Ventas')),
                ('reporte_informe', models.TextField(verbose_name='Reporte del Informe')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sucursal', verbose_name='Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha del Pago')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.banco', verbose_name='Banco')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.metodopago', verbose_name='Método de Pago')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pedido', verbose_name='Pedido')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipopago', verbose_name='Tipo de Pago')),
            ],
        ),
    ]
