# Generated by Django 5.2.1 on 2025-05-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dir_usuario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Usuario'),
        ),
    ]
